// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzrpcqdsdoqyturbraaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6cnBjcWRzZG9xeXR1cmJyYWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NTExNjMsImV4cCI6MjA0OTMyNzE2M30.PonQ7LmkUhZi5Wl_KVNqrQob3gxcgNJ6NWo0VKdH5cM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);